version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: estoque_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - estoque_network
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=estoque_db
      - DB_USERNAME=estoque_user
      - DB_PASSWORD=admin

  nginx:
    image: nginx:alpine
    container_name: estoque_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - estoque_network
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: estoque_mysql
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: estoque_db
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_PASSWORD: admin
      MYSQL_USER: estoque_user
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - estoque_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-padmin"]
      interval: 5s
      timeout: 3s
      retries: 10

networks:
  estoque_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local

